### ISSUE TITLE
TanStack Migration

### ISSUE THREAD

**Issue by leighmacdonald** [leighmacdonald/gbans#465]
There is currently a fair amount of bugs and inconsistencies between various unrelated components to accomplish the same that these libraries provide in a more cohesive manner.

- [x] `@tanstack/react-router` - Replaces a few different libs like react-router-dom, useURLState, history with a single cohesive setup. Currently there is some statemanagement problems with these not playing nice with eachother. #464 
- [x] `@tanstack/react-query` - Not currently experiencing huge breaking issues with current setup, but the added caching and response state updates to, for example new table entries, are a nice addition and should clean up a lot of unnecessary code.  #483 
- [x] `@tanstack/react-form` - Formik is *fine* but has various issues with fighting with url state.  #483 
- [x] `@tanstack/react-table` (maybe) - Current custom table implementation works well enough, but could be nice to ease some development effort long term.  #468   #483 

Some stuff is currently unsupported and may need custom helpers implemented:
- `Sentry.BrowserTracing` - No compatible version for tanstack (yet). But custom shims possible.
